apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-nodeapp-example
  annotations:
    description: my very first kubernetes deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-nodeapp-example-label
  template:
    metadata:
      name: kubernetes-nodeapp-example-spec
      labels:
        app: kubernetes-nodeapp-example-label
    spec:
      containers:
        - image: germmand/kubernetes-test:1.0.0
          name: kubernetes-nodeapp-example-container
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-nodeapp-service
spec:
  selector:
    app: kubernetes-nodeapp-example-label
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 8080
  type: LoadBalancer
